import { DataTypes, InferAttributes, InferCreationAttributes, CreationOptional, Model } from 'sequelize';
import sequelize from '../connection';

class RecordDetails1 extends Model {
}

RecordDetails1.init(
  {
    id: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true,
      allowNull: false,
    },
    // 40 Small Text Fields (col1 to col40)
    col1: { type: DataTypes.STRING, allowNull: false },
    col2: { type: DataTypes.STRING, allowNull: false },
    col3: { type: DataTypes.STRING, allowNull: false },
    col4: { type: DataTypes.STRING, allowNull: false },
    col5: { type: DataTypes.STRING, allowNull: false },
    col6: { type: DataTypes.STRING, allowNull: false },
    col7: { type: DataTypes.STRING, allowNull: false },
    col8: { type: DataTypes.STRING, allowNull: false },
    col9: { type: DataTypes.STRING, allowNull: false },
    col10: { type: DataTypes.STRING, allowNull: false },
    col11: { type: DataTypes.STRING, allowNull: false },
    col12: { type: DataTypes.STRING, allowNull: false },
    col13: { type: DataTypes.STRING, allowNull: false },
    col14: { type: DataTypes.STRING, allowNull: false },
    col15: { type: DataTypes.STRING, allowNull: false },
    col16: { type: DataTypes.STRING, allowNull: false },
    col17: { type: DataTypes.STRING, allowNull: false },
    col18: { type: DataTypes.STRING, allowNull: false },
    col19: { type: DataTypes.STRING, allowNull: false },
    col20: { type: DataTypes.STRING, allowNull: false },
    col21: { type: DataTypes.STRING, allowNull: false },
    col22: { type: DataTypes.STRING, allowNull: false },
    col23: { type: DataTypes.STRING, allowNull: false },
    col24: { type: DataTypes.STRING, allowNull: false },
    col25: { type: DataTypes.STRING, allowNull: false },
    col26: { type: DataTypes.STRING, allowNull: false },
    col27: { type: DataTypes.STRING, allowNull: false },
    col28: { type: DataTypes.STRING, allowNull: false },
    col29: { type: DataTypes.STRING, allowNull: false },
    col30: { type: DataTypes.STRING, allowNull: false },
    col31: { type: DataTypes.STRING, allowNull: false },
    col32: { type: DataTypes.STRING, allowNull: false },
    col33: { type: DataTypes.STRING, allowNull: false },
    col34: { type: DataTypes.STRING, allowNull: false },
    col35: { type: DataTypes.STRING, allowNull: false },
    col36: { type: DataTypes.STRING, allowNull: false },
    col37: { type: DataTypes.STRING, allowNull: false },
    col38: { type: DataTypes.STRING, allowNull: false },
    col39: { type: DataTypes.STRING, allowNull: false },
    col40: { type: DataTypes.STRING, allowNull: false },

    // 10 Large Text Fields (col41 to col50)
    col41: { type: DataTypes.STRING, allowNull: false },
    col42: { type: DataTypes.STRING, allowNull: false },
    col43: { type: DataTypes.STRING, allowNull: false },
    col44: { type: DataTypes.STRING, allowNull: false },
    col45: { type: DataTypes.STRING, allowNull: false },
    col46: { type: DataTypes.STRING, allowNull: false },
    col47: { type: DataTypes.STRING, allowNull: false },
    col48: { type: DataTypes.STRING, allowNull: false },
    col49: { type: DataTypes.STRING, allowNull: false },
    col50: { type: DataTypes.STRING, allowNull: false },

    // 40 Integer Fields (col51 to col90)
    col51: { type: DataTypes.INTEGER, allowNull: false },
    col52: { type: DataTypes.INTEGER, allowNull: false },
    col53: { type: DataTypes.INTEGER, allowNull: false },
    col54: { type: DataTypes.INTEGER, allowNull: false },
    col55: { type: DataTypes.INTEGER, allowNull: false },
    col56: { type: DataTypes.INTEGER, allowNull: false },
    col57: { type: DataTypes.INTEGER, allowNull: false },
    col58: { type: DataTypes.INTEGER, allowNull: false },
    col59: { type: DataTypes.INTEGER, allowNull: false },
    col60: { type: DataTypes.INTEGER, allowNull: false },
    col61: { type: DataTypes.INTEGER, allowNull: false },
    col62: { type: DataTypes.INTEGER, allowNull: false },
    col63: { type: DataTypes.INTEGER, allowNull: false },
    col64: { type: DataTypes.INTEGER, allowNull: false },
    col65: { type: DataTypes.INTEGER, allowNull: false },
    col66: { type: DataTypes.INTEGER, allowNull: false },
    col67: { type: DataTypes.INTEGER, allowNull: false },
    col68: { type: DataTypes.INTEGER, allowNull: false },
    col69: { type: DataTypes.INTEGER, allowNull: false },
    col70: { type: DataTypes.INTEGER, allowNull: false },
    col71: { type: DataTypes.INTEGER, allowNull: false },
    col72: { type: DataTypes.INTEGER, allowNull: false },
    col73: { type: DataTypes.INTEGER, allowNull: false },
    col74: { type: DataTypes.INTEGER, allowNull: false },
    col75: { type: DataTypes.INTEGER, allowNull: false },
    col76: { type: DataTypes.INTEGER, allowNull: false },
    col77: { type: DataTypes.INTEGER, allowNull: false },
    col78: { type: DataTypes.INTEGER, allowNull: false },
    col79: { type: DataTypes.INTEGER, allowNull: false },
    col80: { type: DataTypes.INTEGER, allowNull: false },
    col81: { type: DataTypes.INTEGER, allowNull: false },
    col82: { type: DataTypes.INTEGER, allowNull: false },
    col83: { type: DataTypes.INTEGER, allowNull: false },
    col84: { type: DataTypes.INTEGER, allowNull: false },
    col85: { type: DataTypes.INTEGER, allowNull: false },
    col86: { type: DataTypes.INTEGER, allowNull: false },
    col87: { type: DataTypes.INTEGER, allowNull: false },
    col88: { type: DataTypes.INTEGER, allowNull: false },
    col89: { type: DataTypes.INTEGER, allowNull: false },
    col90: { type: DataTypes.INTEGER, allowNull: false },

    // 20 Date Fields (col91 to col110)
    col91: { type: DataTypes.DATE, allowNull: false },
    col92: { type: DataTypes.DATE, allowNull: false },
    col93: { type: DataTypes.DATE, allowNull: false },
    col94: { type: DataTypes.DATE, allowNull: false },
    col95: { type: DataTypes.DATE, allowNull: false },
    col96: { type: DataTypes.DATE, allowNull: false },
    col97: { type: DataTypes.DATE, allowNull: false },
    col98: { type: DataTypes.DATE, allowNull: false },
    col99: { type: DataTypes.DATE, allowNull: false },
    col100: { type: DataTypes.DATE, allowNull: false },
    col101: { type: DataTypes.DATE, allowNull: false },
    col102: { type: DataTypes.DATE, allowNull: false },
    col103: { type: DataTypes.DATE, allowNull: false },
    col104: { type: DataTypes.DATE, allowNull: false },
    col105: { type: DataTypes.DATE, allowNull: false },
    col106: { type: DataTypes.DATE, allowNull: false },
    col107: { type: DataTypes.DATE, allowNull: false },
    col108: { type: DataTypes.DATE, allowNull: false },
    col109: { type: DataTypes.DATE, allowNull: false },
    col110: { type: DataTypes.DATE, allowNull: false },

    // 20 Checkbox Fields (col111 to col130)
    col111: { type: DataTypes.BOOLEAN, allowNull: false },
    col112: { type: DataTypes.BOOLEAN, allowNull: false },
    col113: { type: DataTypes.BOOLEAN, allowNull: false },
    col114: { type: DataTypes.BOOLEAN, allowNull: false },
    col115: { type: DataTypes.BOOLEAN, allowNull: false },
    col116: { type: DataTypes.BOOLEAN, allowNull: false },
    col117: { type: DataTypes.BOOLEAN, allowNull: false },
    col118: { type: DataTypes.BOOLEAN, allowNull: false },
    col119: { type: DataTypes.BOOLEAN, allowNull: false },
    col120: { type: DataTypes.BOOLEAN, allowNull: false },
    col121: { type: DataTypes.BOOLEAN, allowNull: false },
    col122: { type: DataTypes.BOOLEAN, allowNull: false },
    col123: { type: DataTypes.BOOLEAN, allowNull: false },
    col124: { type: DataTypes.BOOLEAN, allowNull: false },
    col125: { type: DataTypes.BOOLEAN, allowNull: false },
    col126: { type: DataTypes.BOOLEAN, allowNull: false },
    col127: { type: DataTypes.BOOLEAN, allowNull: false },
    col128: { type: DataTypes.BOOLEAN, allowNull: false },
    col129: { type: DataTypes.BOOLEAN, allowNull: false },
    col130: { type: DataTypes.BOOLEAN, allowNull: false },

  },
  {
    sequelize,
    modelName: 'RecordDetails1',
    tableName: 'record_details_1',  // Set the table name for this model
    timestamps: true, // Add `createdAt` and `updatedAt`
  }
);
sequelize.sync()
  .then(() => console.log('Table created successfully!'))
  .catch((err) => console.log('Error creating table:', err));
export default RecordDetails1;
