import { DataTypes, Model } from 'sequelize';
import sequelize from '../connection';

class SubRecordDetails1 extends Model {}

SubRecordDetails1.init(
  {
    id: {
      type: DataTypes.INTEGER,
      primaryKey: true,
      autoIncrement: true,
      allowNull: false,
    },

    // 40 Small Text Fields (subcol1 to subcol40)
    subcol1: { type: DataTypes.STRING, allowNull: false },
    subcol2: { type: DataTypes.STRING, allowNull: false },
    subcol3: { type: DataTypes.STRING, allowNull: false },
    subcol4: { type: DataTypes.STRING, allowNull: false },
    subcol5: { type: DataTypes.STRING, allowNull: false },
    subcol6: { type: DataTypes.STRING, allowNull: false },
    subcol7: { type: DataTypes.STRING, allowNull: false },
    subcol8: { type: DataTypes.STRING, allowNull: false },
    subcol9: { type: DataTypes.STRING, allowNull: false },
    subcol10: { type: DataTypes.STRING, allowNull: false },
    subcol11: { type: DataTypes.STRING, allowNull: false },
    subcol12: { type: DataTypes.STRING, allowNull: false },
    subcol13: { type: DataTypes.STRING, allowNull: false },
    subcol14: { type: DataTypes.STRING, allowNull: false },
    subcol15: { type: DataTypes.STRING, allowNull: false },
    subcol16: { type: DataTypes.STRING, allowNull: false },
    subcol17: { type: DataTypes.STRING, allowNull: false },
    subcol18: { type: DataTypes.STRING, allowNull: false },
    subcol19: { type: DataTypes.STRING, allowNull: false },
    subcol20: { type: DataTypes.STRING, allowNull: false },
    subcol21: { type: DataTypes.STRING, allowNull: false },
    subcol22: { type: DataTypes.STRING, allowNull: false },
    subcol23: { type: DataTypes.STRING, allowNull: false },
    subcol24: { type: DataTypes.STRING, allowNull: false },
    subcol25: { type: DataTypes.STRING, allowNull: false },
    subcol26: { type: DataTypes.STRING, allowNull: false },
    subcol27: { type: DataTypes.STRING, allowNull: false },
    subcol28: { type: DataTypes.STRING, allowNull: false },
    subcol29: { type: DataTypes.STRING, allowNull: false },
    subcol30: { type: DataTypes.STRING, allowNull: false },
    subcol31: { type: DataTypes.STRING, allowNull: false },
    subcol32: { type: DataTypes.STRING, allowNull: false },
    subcol33: { type: DataTypes.STRING, allowNull: false },
    subcol34: { type: DataTypes.STRING, allowNull: false },
    subcol35: { type: DataTypes.STRING, allowNull: false },
    subcol36: { type: DataTypes.STRING, allowNull: false },
    subcol37: { type: DataTypes.STRING, allowNull: false },
    subcol38: { type: DataTypes.STRING, allowNull: false },
    subcol39: { type: DataTypes.STRING, allowNull: false },
    subcol40: { type: DataTypes.STRING, allowNull: false },

    // 10 Large Text Fields (subcol41 to subcol50)
    subcol41: { type: DataTypes.STRING, allowNull: false },
    subcol42: { type: DataTypes.STRING, allowNull: false },
    subcol43: { type: DataTypes.STRING, allowNull: false },
    subcol44: { type: DataTypes.STRING, allowNull: false },
    subcol45: { type: DataTypes.STRING, allowNull: false },
    subcol46: { type: DataTypes.STRING, allowNull: false },
    subcol47: { type: DataTypes.STRING, allowNull: false },
    subcol48: { type: DataTypes.STRING, allowNull: false },
    subcol49: { type: DataTypes.STRING, allowNull: false },
    subcol50: { type: DataTypes.STRING, allowNull: false },

    // 40 Integer Fields (subcol51 to subcol90)
    subcol51: { type: DataTypes.INTEGER, allowNull: false },
    subcol52: { type: DataTypes.INTEGER, allowNull: false },
    subcol53: { type: DataTypes.INTEGER, allowNull: false },
    subcol54: { type: DataTypes.INTEGER, allowNull: false },
    subcol55: { type: DataTypes.INTEGER, allowNull: false },
    subcol56: { type: DataTypes.INTEGER, allowNull: false },
    subcol57: { type: DataTypes.INTEGER, allowNull: false },
    subcol58: { type: DataTypes.INTEGER, allowNull: false },
    subcol59: { type: DataTypes.INTEGER, allowNull: false },
    subcol60: { type: DataTypes.INTEGER, allowNull: false },
    subcol61: { type: DataTypes.INTEGER, allowNull: false },
    subcol62: { type: DataTypes.INTEGER, allowNull: false },
    subcol63: { type: DataTypes.INTEGER, allowNull: false },
    subcol64: { type: DataTypes.INTEGER, allowNull: false },
    subcol65: { type: DataTypes.INTEGER, allowNull: false },
    subcol66: { type: DataTypes.INTEGER, allowNull: false },
    subcol67: { type: DataTypes.INTEGER, allowNull: false },
    subcol68: { type: DataTypes.INTEGER, allowNull: false },
    subcol69: { type: DataTypes.INTEGER, allowNull: false },
    subcol70: { type: DataTypes.INTEGER, allowNull: false },
    subcol71: { type: DataTypes.INTEGER, allowNull: false },
    subcol72: { type: DataTypes.INTEGER, allowNull: false },
    subcol73: { type: DataTypes.INTEGER, allowNull: false },
    subcol74: { type: DataTypes.INTEGER, allowNull: false },
    subcol75: { type: DataTypes.INTEGER, allowNull: false },
    subcol76: { type: DataTypes.INTEGER, allowNull: false },
    subcol77: { type: DataTypes.INTEGER, allowNull: false },
    subcol78: { type: DataTypes.INTEGER, allowNull: false },
    subcol79: { type: DataTypes.INTEGER, allowNull: false },
    subcol80: { type: DataTypes.INTEGER, allowNull: false },
    subcol81: { type: DataTypes.INTEGER, allowNull: false },
    subcol82: { type: DataTypes.INTEGER, allowNull: false },
    subcol83: { type: DataTypes.INTEGER, allowNull: false },
    subcol84: { type: DataTypes.INTEGER, allowNull: false },
    subcol85: { type: DataTypes.INTEGER, allowNull: false },
    subcol86: { type: DataTypes.INTEGER, allowNull: false },
    subcol87: { type: DataTypes.INTEGER, allowNull: false },
    subcol88: { type: DataTypes.INTEGER, allowNull: false },
    subcol89: { type: DataTypes.INTEGER, allowNull: false },
    subcol90: { type: DataTypes.INTEGER, allowNull: false },

    // 20 Date Fields (subcol91 to subcol110)
    subcol91: { type: DataTypes.DATE, allowNull: false },
    subcol92: { type: DataTypes.DATE, allowNull: false },
    subcol93: { type: DataTypes.DATE, allowNull: false },
    subcol94: { type: DataTypes.DATE, allowNull: false },
    subcol95: { type: DataTypes.DATE, allowNull: false },
    subcol96: { type: DataTypes.DATE, allowNull: false },
    subcol97: { type: DataTypes.DATE, allowNull: false },
    subcol98: { type: DataTypes.DATE, allowNull: false },
    subcol99: { type: DataTypes.DATE, allowNull: false },
    subcol100: { type: DataTypes.DATE, allowNull: false },
    subcol101: { type: DataTypes.DATE, allowNull: false },
    subcol102: { type: DataTypes.DATE, allowNull: false },
    subcol103: { type: DataTypes.DATE, allowNull: false },
    subcol104: { type: DataTypes.DATE, allowNull: false },
    subcol105: { type: DataTypes.DATE, allowNull: false },
    subcol106: { type: DataTypes.DATE, allowNull: false },
    subcol107: { type: DataTypes.DATE, allowNull: false },
    subcol108: { type: DataTypes.DATE, allowNull: false },
    subcol109: { type: DataTypes.DATE, allowNull: false },
    subcol110: { type: DataTypes.DATE, allowNull: false },

    // 20 Checkbox Fields (subcol111 to subcol130)
    subcol111: { type: DataTypes.BOOLEAN, allowNull: false },
    subcol112: { type: DataTypes.BOOLEAN, allowNull: false },
    subcol113: { type: DataTypes.BOOLEAN, allowNull: false },
    subcol114: { type: DataTypes.BOOLEAN, allowNull: false },
    subcol115: { type: DataTypes.BOOLEAN, allowNull: false },
    subcol116: { type: DataTypes.BOOLEAN, allowNull: false },
    subcol117: { type: DataTypes.BOOLEAN, allowNull: false },
    subcol118: { type: DataTypes.BOOLEAN, allowNull: false },
    subcol119: { type: DataTypes.BOOLEAN, allowNull: false },
    subcol120: { type: DataTypes.BOOLEAN, allowNull: false },
    subcol121: { type: DataTypes.BOOLEAN, allowNull: false },
    subcol122: { type: DataTypes.BOOLEAN, allowNull: false },
    subcol123: { type: DataTypes.BOOLEAN, allowNull: false },
    subcol124: { type: DataTypes.BOOLEAN, allowNull: false },
    subcol125: { type: DataTypes.BOOLEAN, allowNull: false },
    subcol126: { type: DataTypes.BOOLEAN, allowNull: false },
    subcol127: { type: DataTypes.BOOLEAN, allowNull: false },
    subcol128: { type: DataTypes.BOOLEAN, allowNull: false },
    subcol129: { type: DataTypes.BOOLEAN, allowNull: false },
    subcol130: { type: DataTypes.BOOLEAN, allowNull: false },
  },
  {
    sequelize,
    modelName: 'SubRecordDetails1',
    tableName: 'sub_record_details_1',
    timestamps: true, // Add `createdAt` and `updatedAt`
  }
);

sequelize.sync()
  .then(() => console.log('Table created successfully!'))
  .catch((err) => console.log('Error creating table:', err));

export default SubRecordDetails1;
